Flaskserver 2
Capstone-Projects-2020-Spring/TwitterTrends pull request #11
Opened 2020-02-29 20:55 UTC by tug73060

1) The front-end (HTML and bootstrap) is linked with the server. 
All the changes to the bootstrap should be made in the _static_ folder. 

2) Run the server with __init__.py

2020-03-03 22:11 UTC, BareBeaverBat requested changes

2020-03-03 22:11 UTC, BareBeaverBat commented on appserver/static/index.html
> +<!DOCTYPE html>
Why is this file in both the static and template folders? 
Also, this flask documentation seems to say that html should mostly go in the templates folder while the static folder mostly holds css & js files:
https://flask.palletsprojects.com/en/1.1.x/tutorial/static/
https://flask.palletsprojects.com/en/1.1.x/tutorial/templates/

2020-03-05 20:47 UTC, tug73060 commented
Deleted index.html in _static_ folder and other extra html files in _templates_ folder

2020-03-06 01:40 UTC, BareBeaverBat approved these changes

2020-03-06 01:40 UTC, merged